### PR TITLE
Logs are added to UI at certain intervals

### PR DESCRIPTION
**Pull request by emm1R**
A lot of logs could freeze the UI. Hopefully, now that logs are only added every second, this will prevent freezing.

### CODE REVIEW

**Review by kkmattil — APPROVED** [review]
OK

**Review by blankdots — CHANGES_REQUESTED** [review]
please update the change log and bump the version

**Comment by blankdots** [comment]
I think maybe we should introduce a quiet mode where we suppress all logs, @emm1R how complicated would that be ?

**Comment by emm1R** [comment]
You mean that the user cannot see the logs at all? In UI and CLI?

**Comment by blankdots** [comment]
> You mean that the user cannot see the logs at all? In UI and CLI?

yes, in both. Just asking how complicated it would be.

**Comment by blankdots** [comment]
> > > You mean that the user cannot see the logs at all? In UI and CLI?
> > 
> > 
> > yes, in both. Just asking how complicated it would be.
> 
> Not complicated

maybe we can do that as part of another PR, but not a high priority

**Review by blankdots — APPROVED** [review]

**Pull request merged**
